In [1]:
import numpy as np

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}\quad
\overrightarrow{u}=\begin{pmatrix}
x\\ 
y
\end{pmatrix}\quad A\cdot\overrightarrow{u}=\lambda\cdot\overrightarrow{u}\\
\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}\cdot\begin{pmatrix}
x\\ 
y
\end{pmatrix}=\lambda\cdot\begin{pmatrix}
x\\ 
y
\end{pmatrix}\to\begin{pmatrix}
-x & -6\cdot y\\ 
2\cdot x & 6\cdot y
\end{pmatrix}=\begin{pmatrix}
\lambda\cdot x\\ 
\lambda\cdot y
\end{pmatrix}\\
\begin{cases}
-x-6\cdot y = \lambda\cdot x \\
2\cdot x + 6\cdot y = \lambda\cdot y
\end{cases}
\begin{cases}
-x-6\cdot y - \lambda\cdot x = 0\\
2\cdot x + 6\cdot y - \lambda\cdot y = 0
\end{cases}
\begin{cases}
(-1-\lambda)\cdot x-6\cdot y = 0\\
2\cdot x + y\cdot(6 - \lambda) = 0
\end{cases}\quad
\overrightarrow{u}=\begin{pmatrix}
x\\ 
y
\end{pmatrix}\neq\begin{pmatrix}
0\\ 
0
\end{pmatrix}\\
\begin{vmatrix}
(-1-\lambda) & -6\\
2 & (6 - \lambda)
\end{vmatrix}=0\quad
(-1-\lambda)\cdot(6 - \lambda)-2\cdot(-6)=0\quad
\lambda^2-5\cdot\lambda-6+12=0\\
\lambda^2-5\cdot\lambda+6=0
D=b^2-4\cdot a\cdot c=25 - \cdot 1\cdot 6=25-24=1\to
\sqrt{D}=1\\
\lambda_{1,2}=\frac{-b\pm \sqrt{D}}{2\cdot a}\quad
\lambda_1=\frac{5-1}{2}=2\quad
\lambda_2=\frac{5+1}{2}=3\\
\begin{cases}
(-1-\lambda)\cdot x-6\cdot y = 0\\
2\cdot x + y\cdot(6 - \lambda) = 0
\end{cases}\quad \lambda=\lambda_1=2\quad\begin{cases}-3\cdot x-6\cdot y = 0\\
2\cdot x + y\cdot 4 = 0
\end{cases}\quad
\begin{vmatrix}
-3 & -6\\
2 & 4
\end{vmatrix}\\
x= -2\cdot y\to y=-1\quad x=-2\cdot(-1)=2\quad\begin{cases}-3\cdot 2-6\cdot (-1) = 0\\
2\cdot 2 - 1\cdot 4 = 0
\end{cases}=\begin{cases}-6+6 = 0\\
4 - 4 = 0
\end{cases}\\
\overrightarrow{u}=\begin{pmatrix}
2\\ 
-1
\end{pmatrix}\\
\begin{vmatrix}
(-1-\lambda) & -6\\
2 & (6 - \lambda)
\end{vmatrix}\quad \lambda=\lambda_2=3\quad
\to \quad
\begin{vmatrix}
(-1-3) & -6\\
2 & (6 - 3)
\end{vmatrix}=
\begin{vmatrix}
-4 & -6\\
2 & 3
\end{vmatrix}\\
x= -\frac{3}{2}\cdot y\to y=-2\quad x=-\frac{3}{2}\cdot(-2)=3\quad
\begin{cases}-4\cdot 3-6\cdot (-2) = 0\\
2\cdot 3 + 3\cdot (-2) = 0
\end{cases}=
\begin{cases}-12+12 = 0\\
6 - 6 = 0
\end{cases}\\
\overrightarrow{u}=\begin{pmatrix}
3\\ 
-2
\end{pmatrix}\\\\
\text{Собственные значения: }\lambda_1=2,\quad\lambda_2=3\\
\text{Собственные вектора: }\overrightarrow{u_1}=\begin{pmatrix}
2\\ 
-1
\end{pmatrix},\quad\overrightarrow{u_2}=\begin{pmatrix}
3\\ 
-2
\end{pmatrix}$

 

In [2]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.



$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}\cdot\begin{pmatrix}
x\\ 
y
\end{pmatrix}=\lambda\cdot\begin{pmatrix}
x\\ 
y
\end{pmatrix}\to\begin{pmatrix}
-1\cdot x & 0\cdot y\\ 
0\cdot x & -1\cdot y
\end{pmatrix}=\begin{pmatrix}
\lambda\cdot x\\ 
\lambda\cdot y
\end{pmatrix}\\
\begin{cases}
-x-0\cdot y = \lambda\cdot x \\
0\cdot x -1\cdot y = \lambda\cdot y
\end{cases}
\begin{cases}
-x - \lambda\cdot x = 0\\
-y - \lambda\cdot y = 0
\end{cases}
\begin{cases}
(-1-\lambda)\cdot x = 0\\
(-1-\lambda)\cdot y = 0
\end{cases}\quad
\overrightarrow{u}=\begin{pmatrix}
x\\ 
y
\end{pmatrix}\neq\begin{pmatrix}
0\\ 
0
\end{pmatrix}\\
\begin{vmatrix}
(-1-\lambda) & 0\\
0 & (-1 - \lambda)
\end{vmatrix}=0\quad
(-1-\lambda)\cdot(-1 - \lambda)-0=0\quad
\lambda^2+2\cdot\lambda+1=0\\
D=b^2-4\cdot a\cdot c=4-4=0$

In [3]:
a_2 = np.array([[-1, 0], [0, -1]])
w_2, v_2 = np.linalg.eig(a)

print(f'Матрица A:\n{a_2}')
print(f'Собственные значения:\n{w_2}')
print(f'Собственные векторы:\n{v_2}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}
$

Из этого будет следовать, что 

$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}$

Таким образом, вектор  $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=2.$

In [4]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2.00000002 1.99999998]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
4
\end{pmatrix}
$

$\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
2\lambda=3
\end{cases}$

Таким образом, вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$

In [5]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
