In [1]:
import numpy as np

## Практическое задание(3)
### Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$ 
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
   
    Произведение матриц в пунктах а)б) - не определенны так как число строк "m" первой матрицы должно быть равно числу столбцов "n" второй матрицы, а число столбцов "n" первой матрицы должно быть равно число строк "m" второй матрицы;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
   
    Размерность результирующей матрицы будет 8х8
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
    Размерность результирующей матрицы будет 4х4
    


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$



Сумма матриц

$A+B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} +\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=\begin{pmatrix}
1+4 & -2+(-1)\\ 
3+0 & 0+5
\end{pmatrix}=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

Произведение матриц

$A\cdot B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=\begin{pmatrix}
1\cdot4+(-2)\cdot 0 & 1\cdot (-1) + (-2)\cdot 5\\ 
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}\n'
      f'Матрица B\n{B}\n'
      f'Сумма матриц AB\n{A + B}\n'
      f'Произведение матриц AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Сумма матриц AB
[[ 5 -3]
 [ 3  5]]
Произведение матриц AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    


$3A-2B+4C=3\cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2\cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+ 4\cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} - \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}+ \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}=\begin{pmatrix}
3-0+8 & 21-10+(-16)\\ 
9-4+4 & -18-(-2)+4
\end{pmatrix}=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [3]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'Матрица 3𝐴−2𝐵+4𝐶\n{3*A-2*B+4*C}\n')

Матрица 3𝐴−2𝐵+4𝐶
[[ 11  -5]
 [  9 -12]]



__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.



$AA^{T}=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}\cdot\begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix}=\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\
5\cdot4+(-2)\cdot1 & 5\cdot5+(-2)\cdot(-2) & 5\cdot2+(-2)\cdot3\\
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$

$A^{T}A=\begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix}\cdot\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}=\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\ 
1\cdot4+(-2)\cdot5+3\cdot2 & 1\cdot1+(-2)\cdot(-2)+3\cdot3
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [4]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица:\n{A}\n'
      f'Транспонированная матрица:\n{A.T}\n'
      f'𝐴𝐴^T:\n{np.dot(A, A.T)}\n'
      f'𝐴^TA:\n{np.dot(A.T, A)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
𝐴𝐴^T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
𝐴^TA:
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
# TODO
A = [[1, -2], [3, 0]]
B = [[4, -1], [0, 5]]
res = [[A[0][0]*B[0][0]+A[0][1]*B[1][0], A[0][0]*B[0][1]+A[0][1]*B[1][1]],
       [A[1][0]*B[0][0]+A[1][1]*B[1][0], A[1][0]*B[0][1]+A[1][1]*B[1][1]]]
res

def matrix_multiplication():
    pass

## Практическое задание(4)
### Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.


__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}\\
=sinx\cdot sinx-(-cosx\cdot cosx)\\
=sin^2x+cos^2x\\=1$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=4\cdot \begin{vmatrix}
5 & 1\\ 
0 & 9 
\end{vmatrix}-2 \cdot \begin{vmatrix}
0 & 1\\ 
0 & 5 
\end{vmatrix}+3\cdot \begin{vmatrix}
0 & 5\\ 
0 & 0 
\end{vmatrix}=\\
=4\cdot(5\cdot9-1\cdot0)-2\cdot(0\cdot9+1\cdot0)+3\cdot(0\cdot0+5\cdot0)\\
=4\cdot45\\
=180$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=1\cdot \begin{vmatrix}
5 & 6\\ 
8 & 9 
\end{vmatrix}-2 \cdot \begin{vmatrix}
4 & 6\\ 
7 & 9 
\end{vmatrix}+3\cdot \begin{vmatrix}
4 & 5\\ 
7 & 8 
\end{vmatrix}=\\
=1\cdot(5\cdot9-6\cdot8)-2\cdot(4\cdot9+6\cdot7)+3\cdot(4\cdot8+5\cdot7)\\
=1\cdot(45-48)-2\cdot(36+42)+3\cdot(32+35)\\
=-3+12-9\\
=0$$




In [6]:
a = np.array([[np.sin(0), -np.cos(0)], [np.cos(0), np.sin(0)]])
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
v = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица: а\n{a}\n'
      f'Матрица: б\n{b}\n'
      f'Матрица: в\n{v}\n\n'
      f'Определитель: а\n{np.linalg.det(a):.0f}\n'
      f'Определитель: б\n{np.linalg.det(b):.0f}\n'
      f'Определитель: в\n{np.linalg.det(v):.0f}\n')

Матрица: а
[[ 0. -1.]
 [ 1.  0.]]
Матрица: б
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Матрица: в
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Определитель: а
1
Определитель: б
180
Определитель: в
0



__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})=det(A*A)=det(A)\cdot det(A)=4\cdot4=16 - \text{Согласно 9-ому свойству определителя}$;
    
   б) $det(A^{T})=det(A)=4 - \text{Согласно 1-ому свойству определителя}$;
    
   в) $det(2A)=2det(A)= 8  - \text{Согласно 2-ому свойству определителя}$.
   


In [7]:
# TODO fix
A = np.array([[6, 2], [1, 1]])
A_2= A*2
print(f'Определитель матрицы 𝐴: \n{np.linalg.det(A):.0f}\n'
      f'Определитель матрицы 𝐴^2: \n{np.linalg.det(A*A):.0f}\n'
      f'Определитель матрицы 𝐴^T: \n{np.linalg.det(A.T):.0f}\n'
      f'Определитель матрицы 2𝐴: \n{np.linalg.det(A_2):.0f}\n')

Определитель матрицы 𝐴: 
4
Определитель матрицы 𝐴^2: 
32
Определитель матрицы 𝐴^T: 
4
Определитель матрицы 2𝐴: 
16



__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.



__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$